### ISSUE TITLE
EC2 Auto Scaling lifecycle manager for EC2 Spot Instances interruptions for Kubernetes on AWS

### ISSUE THREAD

**Issue by schmutze** [aws/ec2-spot-instances-integrations-roadmap#15]
We are researching a tool that implements [EC2 Auto Scaling lifecycle hooks](https://docs.aws.amazon.com/autoscaling/ec2/userguide/lifecycle-hooks.html) to manage K8s pods during EC2 instance interruptions. 

We'd love to hear your requirements and feedback as we research this project!

**Comment by jillmon** [comment]
This feature is now available within the [AWS Node Termination Handler](https://github.com/aws/aws-node-termination-handler) project. Using the queue processor mode will allow you to manage EC2 Auto Scaling lifecycle hooks and more.
