### ISSUE TITLE
Improved EC2 Spot Instances support in EKSCTL

### ISSUE THREAD

**Issue by schmutze** [aws/ec2-spot-instances-integrations-roadmap#9]
Improved EC2 Spot Instances support in [EKSCTL](https://eksctl.io/)**

We recently added support for the spotAllocationStrategy field in the instancesDistribution configuration block for node groups. This allows for spot configurations to choose to use lowest-price (defaulted in the API if not specified) or capacity-optimized. The capacity-optimized strategy will choose the deepest capacity pools from the instance-types specified.

https://github.com/weaveworks/eksctl/pull/1883

Additionally, we are working to integrate the Amazon EC2 Instance Selector into EKSCTL for improved EC2 Spot Instances best practices support.

We'd love to hear your requirements and feedback for this project!

**Comment by kholisrag** [comment]
when we use mixed instance practice like in [here](https://docs.aws.amazon.com/autoscaling/ec2/userguide/asg-purchase-options.html#asg-instances-distribution), use on-demand + spot in one nodegroup / asg

I suggest to `eksctl` to adding label on the node to differentiate on-demand instance and spot instance, so we can use `nodeSelector` in our EKS cluster, that will help our deployment workload to choose, as there is a deployment that we don't tolerate running in on-demand node, and there is workload that we can tolerate in spot instance node, wdyt?

**Comment by dchelupati** [comment]
> when we use mixed instance practice like in [here](https://docs.aws.amazon.com/autoscaling/ec2/userguide/asg-purchase-options.html#asg-instances-distribution), use on-demand + spot in one nodegroup / asg
> 
> I suggest to `eksctl` to adding label on the node to differentiate on-demand instance and spot instance, so we can use `nodeSelector` in our EKS cluster, that will help our deployment workload to choose, as there is a deployment that we don't tolerate running in on-demand node, and there is workload that we can tolerate in spot instance node, wdyt?

can you create OD and Spot node groups separately and label them to achieve the same desired result? also, can you share your workload and how do you decide which should go on OD vs Spot nodes?

**Comment by jillmon** [comment]
This is the first of a series of PRs to implement this feature https://github.com/weaveworks/eksctl/pull/3107
